- .gitignore
- lib/jose.ex
- lib/jose/jwk.ex
- lib/jose/jws.ex
- mix.exs
- mix.lock
This is an initial attempt at documenting the Elixir API of the erlang-jose library. I still have to find more time to dig in deeper on the API to understand its structures.
Although incomplete, this has the base for publishing it to hex and linking the docs to the version. If you run:
```elixir
MIX_ENV=docs mix do deps.get, compile
MIX_ENV=docs mix docs
```
You will see something like:
After that is just a matter of issuing:
```elixir
MIX_ENV=docs mix hex.docs
```
And Hex will show a "(docs)" link. 
@potatosalad What do you think of starting small? This might be helpful in a future version release where people will get more insightful messages from `h JOSE.JWK.verify` in the shell or IDEs.
> Begin documenting the Elixir API

- src/jose_jws.erl
Invoke `jose_jws:sign/4` with non binary payload (e.g. `jose_jws:sign(Key, #{}, #{}, Other)`) causes infinite loop.
> Add missing guards in jose_jws:sign/4

- .travis.yml
This adds Elixir version 1.1 and 1.2 in travis. Because 1.2 depends only on Erlang 18, there is also a matrix config to exclude it form running in Erlang 17.
In my fork, the build failed because running the test suite in Erlang 17.5 takes more than 10 minutes without output. This makes Travis to abort the build. Perhaps some output in the tests may satisfy Travis.
> Added Elixir versions to travis.

- src/jose_jwa_pkcs1.erl
- src/jose_jwe_alg_aes_kw.erl
- src/jose_jwe_alg_pbes2.erl
- src/jose_jwe_enc_aes.erl
- src/jose_jwk_kty.erl
- src/jose_jwk_kty_oct.erl
- src/jose_jwk_pem.erl
Elixir 1.3 treats all warnings as errors, Erlang OTP 19.0 throws deprecation warnings for `crypto:rand_bytes`. Replaced each call with `strong_rand_bytes` instead.
> Replace all instances of rand_bytes with strong_rand_bytes

- README.md
For projects that depend on `jose` directly and are released with deploy tools (`exrm`, etc.)
Without this code addition, it has been my experience and others I work with that my releases don't get `jose` required at runtime.  This should help alleviate confusion.
> Updating documentation to describe how to include jose with released applications

- mix.exs
When using Elixir 1.4 new warnings are raised:
```
warning: variable "erlc_options" does not exist and is being expanded to "erlc_options()", please use parentheses to remove the ambiguity or change the variable name
/home/alexandrubagu/devel/antidote/deps/jose/mix.exs:8
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
/home/alexandrubagu/devel/antidote/deps/jose/mix.exs:11
warning: variable "description" does not exist and is being expanded to "description()", please use parentheses to remove the ambiguity or change the variable name
/home/alexandrubagu/devel/antidote/deps/jose/mix.exs:19
warning: variable "package" does not exist and is being expanded to "package()", please use …
```
> add parentheses to remove the ambiguity on Elixir 1.4

- src/jose_jwk_kty_ec.erl
* EC Signatures should be 64, 96 or 132 octet sequences according to
https://tools.ietf.org/html/rfc7518#section-3.4
* Previous padding implementation can generate signatures that are
shorter than what is stated in the RFC and other platform
(non-erlang VM) librarys may fail to verify the signature
> Fix cross platform issues of EC signatures

- src/jose_jwt.erl
Hi @potatosalad,
Hope you doing great. I recently stumbled upon strange behavior when JWT verification was stuck. I have found #44 and I decided to fix it. What do you think?
When empty list is being passed to `jose_jwt:sign`, `jose_jwt:verify` and `jose_jwt:verify_strict` it enters infinite loop.
Add additional function definitions that will raise `badarg` error when the empty list will be passed as a key.
The empty list can slip through to the key argument because `jose_jwk:from_pem` returns the empty list if pem file content is invalid.
Fixes #44.
> Fix JWT sign and verify function when key is empty list

- CHANGELOG.md
- Makefile
- include/exception.hrl
- mix.exs
- src/jose.app.src
- src/jose_public_key.erl
Macro to compile without warnings both before R21 and after.
> Add macro to compile without warnings due to new stacktrace syntax.

- lib/jose/jwa.ex
- src/jose_jwa_pkcs1.erl
- use -1 instead of -2 for sign according to RFC7518
- update docs according to RFC7518 and pkeyutl/evp_pkey_ctrl_str
I was looking at the RFC here:
- https://tools.ietf.org/html/rfc7518#section-3.5
This line in section 3.5:
> The size of the salt value is the same size as
the hash function output.
The issue was discovered trying to pass values between this library and an equivalent Python library. I don't think this should cause any backward compatibility problems because we only change to use `-1` for creating the signature but `-2` is still used to verify the signature which should work for the max-length and for the hash-length formats.
> 2019-02-19_fix-pss-saltlen

- Makefile
- erlang.mk
- include/jose_compat.hrl
- src/jose_chacha20_poly1305_crypto.erl
- src/jose_crypto_compat.erl
- src/jose_public_key.erl
- src/jose_server.erl
- src/jose_xchacha20_poly1305_crypto.erl
- src/jwa/jose_jwa.erl
- src/jwa/jose_jwa_aes.erl
- src/jwa/jose_jwa_concat_kdf.erl
- src/jwa/jose_jwa_pkcs1.erl
- src/jwa/jose_jwa_pkcs5.erl
- src/jwe/jose_jwe_enc_aes.erl
- src/jwk/jose_jwk_kty_oct.erl
- test/property_test/jose_jwa_pkcs1_props.erl
Ran tests with both:
make docker-test DOCKER_OTP_VERSION=22.2.1 DOCKER_ELIXIR_VERSION=1.9.4
make docker-test DOCKER_OTP_VERSION=23.0.2 DOCKER_ELIXIR_VERSION=1.10.4
Fixes #87
> Add crypto compat wrapper for OTP 23 deprecations

- mix.exs
I'm getting the following warning when compiling jose with elixir 1.11.
```
warning: Poison.EncodeError.exception/1 defined in application :poison is used by the current application but the current application does not directly depend on :poison. To
fix this, you must do one of:
1. If :poison is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs
2. If :poison is a dependency, make sure it is listed under "def deps" in your mix.exs
3. In case you don't want to add a requirement to :poison, you may optionally skip this warning by adding [xref: [exclude: Poison.EncodeError]] to your "def project" in mix.exs
lib/jose/poison/lexical_encoder.ex:8: JOSE.Poison.LexicalEncodeError.exception/1
```
Use extra_applications, so elixir can infer …
> Use extra_applications

- src/jose_crypto_compat.erl
- src/jose_server.erl
- src/jwa/jose_jwa_aes.erl
This builds off of PR #105 which should be merged first.
Fixes #103 which accounted for 7 CT failures. (#105 fixes the 11 other CT failures present in this library version 1.11.0.)  
So there should be zero failures on OTP 23 after merging these two PRs.
> Fix AES GCM bugs on OTP 23

- rebar.config
As mentioned in https://github.com/potatosalad/erlang-jose/pull/108 , this library is no longer needed.
> Remove dependency on external base64url library, useless since 8e53209

- CHANGELOG.md
The version `1.11.0` was listed twice.
> Correct latest release version in CHANGELOG.md

- .github/workflows/main.yml
Tests are currently failing due to compatibility issues that will be fixed.
> Add OTP 24 to CI

- .github/workflows/main.yml
The captures the common test logs from failed runs as a workflow artifact, for convenience in inspecting failures
> Capture test logs on failure in Github Actions

- src/jose_server.erl
When this module is compiled on Erlang 23 but runs on 24,
ECPrivateKey pattern matching fails due to that record having
a different set of fields as of Erlang 24.
This PR assumes that to detect EC key mode it should be sufficient to only check one
value. I could not think of a reason for private and public key to use different types
in a single record.
Closes #113.
> Handle ECPrivateKey records on Erlang 23 and 24

- .github/workflows/main.yml
- src/jose_public_key.erl
- src/jwa/jose_jwa.erl
The block_decrypt API was deprecated in Erlang 23 and removed in 24. This provides Erlang 24 compatibility.
> Erlang 24 Compatibility

- src/jose.app.src
jose was released and published at hex.pm as 1.11.2, but in .app.src still use 1.11.1.
This forces rebar3 constantly check jose for updates on every action and show wrong
version in `rebar3 tree`. Since 1.11.1 already published as 1.11.2 change app version
to 1.11.3 for adjusting version between `.app.src`, git tag and hex.pm release.
> Adjust jose version

- src/jose_curve25519_otp.erl
- src/jose_curve448_otp.erl
Decided to take a crack at #91. I just have the 25519 curve so far, no 448. I thought to not break previous versions there'd just be an OTP-native implementation developers could choose instead of libdecaf/libsodium. But I'm not that experienced with erlang or crypto, so I had some questions:
1. What's the best way to test this? I had thought I'd just copy the tests for `:jose_jwa_curve25519`, but I haven't been able to run the tests locally (tried docker-build/docker-test and make tests and kept running into snags), so I thought I'd check. In manual testing I just compared the output of these functions to those in `:jose_jwa_curve25519`.
2. What does the module need to do to not cause problems for OTP versions before 23 (I've only tried it in 24)?
> Support Ed25519 in native OTP 23+

- Makefile
- mix.exs
- src/jose_server.erl
- src/json/jose_json_thoas.erl
- test/jose_test.exs
@ericmj sorry to ping you directly but this turned out to be an unexpected blocker for Thoas adoption in RabbitMQ :) If you agree to accept this PR, we'd appreciate a new tag we can depend on.
> Add support for Thoas (a yet another JSON library)

- lib/jose/jwk.ex
- test/jose_test.exs
This idea spawned from [this discussion](https://github.com/joken-elixir/joken/issues/383)
Here is what the output would look like for an elixir client using Joken
```elixir
iex(1)> signer = Joken.Signer.create("HS256", "s3cret")
%Joken.Signer{
jwk: #JOSE.JWK<keys: :undefined, fields: %{}, ...>,
jws: %JOSE.JWS{
alg: {:jose_jws_alg_hmac, :HS256},
b64: :undefined,
fields: %{"typ" => "JWT"}
},
alg: "HS256"
}
```
I am not sure if the `keys` or `fields` defined in the [jose_jwk](https://github.com/potatosalad/erlang-jose/blob/991649695aaccd92c8effb1c1e88e6159fe8e9a6/include/jose_jwk.hrl) record would ever hold private information, but I am hoping that this can start a discussion.
> Hide kty in %JOSE.JWK{} when it is inspected

- src/jose_server.erl
In Openssl 3.0.1 in default configuration, `jose_server.erl` will determine that no `RS*` algorithms are supported for signing. The reason for this is usage of `sha` for DigestType when determining RSA signing supportability.
This breaks various flows even though 2 workarounds exist (both of which are not satisfactory enough in our case):
1) Set JOSE `crypto_fallback` env var to `true`
2) Allow explicitly RSA+SHA1 signatures in openssl config
I propose we change the DigestType to `sha256`, since `sha1` signature creation will probably be disabled in the future on both RHEL 9 and RHEL 10, based on info from [1].
Currently, SHA1+RSA signature creation is not allowed in OpenSSL configuration on public cloud Alma Linux images. Where the config is hardened to disallow certain signature …
> Use 'sha256' instead of 'sha' when validating RSA signing supportability

- lib/jose.ex
- lib/jose/jwt.ex
Just testing the waters here. The Elixir documentation can sometimes be somewhat harder to understand due to the lack of specs, which do a great job (IMO!) of documenting arguments and return values of functions.
Are you interested in this type of work? I think there's a lot we can do with `@typedoc ...`s, spec'ing functions, and adding a few types here and there (say, `@type JOSE.JWT.signed() :: String.t()`.
Thoughts? 🙃 Thanks for the foundational library! 💟
> Add a couple of initial @specs to Elixir

- src/json/jose_json_jiffy.erl
`jiffy` may return an `iolist` instead of a `binary` when encoding big objects (see details [here](https://github.com/davisp/jiffy/issues/220)). This leads to problems inside `jose` as it expects the plaintext to be a `binary` when signing a token (see [here](https://github.com/potatosalad/erlang-jose/blob/main/src/jws/jose_jws.erl#L261)).
> Ensure 'jiffy:encode/1' returns a binary

- mix.exs
Related to https://github.com/potatosalad/erlang-jose/pull/98.
Poison is optionally depended on by JOSE.Poison, which is conditionally compiled in. Mix should know that this dependency exists, so that Poison is compiled first, and available during JOSE's compilation when used.
Since Poison is very heavily depended on, I picked the last few major versions to avoid dependency hell when pulling in other libraries that might still depend on an older version. It seems to me that all of these should be compatible with JOSE.Poison, as I only see it depend on Poison.EncodeError which has been around for a long time.
> Declare Poison as an optional dependency

- lib/jose.ex
@potatosalad follow up to my previous PR. More incoming 🙃
> Add @specs to the JOSE module

- mix.exs
This is just a tiny opinionated documentation change.
I didn't notice all the useful docs in the README, as I was looking at the ex_docs which [defaults to the JOSE module](https://hexdocs.pm/jose/).
This PR changes the default page to the [README](https://hexdocs.pm/jose/readme.html), which has lots of example code and is much more useful.
> Make default ex_doc page the README

- mix.exs
Updates the dialyxir config to only load in test and dev, resolving dep conflicts in Elixir projects.
Resolves warning:
```
Warning: the `dialyxir` application's start function was called, which likely means you
did not add the dependency with the `runtime: false` flag. This is not recommended because
it will mean that unnecessary applications are started, and unnecessary applications are most
likely being added to your PLT file, increasing build time.
```
Resolves deps conflict:
```
Unchecked dependencies for environment dev:
* dialyxir (Hex package)
the :only option for dependency dialyxir
> In mix.exs:
{:dialyxir, "~> 1.0", [env: :prod, hex: "dialyxir", only: [:dev], runtime: false, repo: "hexpm"]}
does not match the :only option calculated for
> In deps/jose/mix.exs:
{:dialyxir, "~> …
```
> Fix dialyxir config

- lib/jose/jwt.ex
> Verify and verify_strict typespec should reference JOSE.JWK.t()

- lib/jose/jwe.ex
Hey there 👋🏾  thanks for the fantastic library! 🎉 
I figured out that there might be a `@spec` error when running dialyzer from my app.
The code is more or less this:
```elixir
jwk
|> JOSE.JWE.block_encrypt(Jason.encode!(payload), %{
"alg" => @alg,
"enc" => @enc
})
|> JOSE.JWE.compact()
|> elem(1)
```
The dialyzer complaint (from my side) is:
```elixir
The function call will not succeed.
JOSE.JWE.compact({%{:alg => atom(), :enc => atom(), :zip => atom()}, %{<<_::16, _::size(8)>> => binary()}}) ::
:ok
def a() do
:ok
end
breaks the contract
(map()) :: {map(), binary()}
```
PS: I am not sure if `{map(), map()}` is 100% correct. Please let me know
> Fix JOSE.JWE.compact/1 @spec

- src/jose_server.erl
- src/json/jose_json_otp.erl
- test/jose_test.exs
Implements #157 
Dialyzer Error is expected for testing with OTP < 27, should pass with #175.
Accidentally removed fork which closed the PR #170, re-opening.
> Support OTP json module
